import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Vault configuration
// If DEV_VAULT is explicitly set, use it; otherwise use default behavior
const DEV_VAULT = "../obsidian-dev-vault";
const PROD_VAULT = "./test-vault";
const PLUGIN_NAME = "obsidian-kadi4mat-sync";

const targetVault = process.env.DEV_VAULT || (prod ? PROD_VAULT : DEV_VAULT);
const pluginDir = `${targetVault}/.obsidian/plugins/${PLUGIN_NAME}`;

console.log(`\n🔨 Building for ${prod ? 'PRODUCTION' : 'DEVELOPMENT'}`);
console.log(`📂 Target: ${pluginDir}\n`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${pluginDir}/main.js`,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
